In [1]:
import numpy as np
import torch

In [3]:
coordinates = torch.from_numpy(np.random.rand(5, 3))
coordinates

tensor([[0.0056, 0.0986, 0.3747],
        [0.6344, 0.2998, 0.4138],
        [0.7228, 0.5758, 0.1470],
        [0.8928, 0.7339, 0.5491],
        [0.2027, 0.3017, 0.5235]], dtype=torch.float64)

In [36]:
duplicated_coordinates = coordinates.unsqueeze(0).broadcast_to((5, 5, 3)).permute(0, 2, 1)

In [39]:
duplicated_coordinates[:, :, 1]

tensor([[0.6344, 0.2998, 0.4138],
        [0.6344, 0.2998, 0.4138],
        [0.6344, 0.2998, 0.4138],
        [0.6344, 0.2998, 0.4138],
        [0.6344, 0.2998, 0.4138]], dtype=torch.float64)

In [37]:
a = coordinates.unsqueeze(-1).broadcast_to(duplicated_coordinates.shape) - duplicated_coordinates

In [35]:
torch.sum((coordinates[0] - coordinates[1]) ** 2) ** 0.5

tensor(0.6615, dtype=torch.float64)

In [33]:
torch.sum(a ** 2, dim = 1) ** 0.5

tensor([[0.0000, 0.6615, 0.8911, 1.1051, 0.3198],
        [0.6615, 0.0000, 0.3939, 0.5230, 0.4455],
        [0.8911, 0.3939, 0.0000, 0.4643, 0.6981],
        [1.1051, 0.5230, 0.4643, 0.0000, 0.8147],
        [0.3198, 0.4455, 0.6981, 0.8147, 0.0000]], dtype=torch.float64)